openapi: 3.0.0
info:
  title: Job Board API
  description: API for managing Job postings
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local Development
paths:
  /newJob:
    $ref: "./paths/Jobs.yaml"
components:
  schemas:
    JobInput:
      $ref: "./components/schemas/jobs/Job.yaml"
    JobResponse:
      $ref: "./components/schemas/jobs/JobResponse.yaml"
