openapi: 3.0.0
info:
  title: Job Board API
  description: API for managing Job postings
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local Development
paths:
  /newJob:
    post:
      summary: Create a new job
      tags:
        - Jobs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
      responses:
        '201':
          description: Job created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResponse'
        '400':
          description: Validation error
        '409':
          description: Job already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Job already exists
        '500':
          description: Internal server error
  /updateJob/{id}:
    put:
      summary: Update Job
      tags:
        - Jobs
      description: Update an existing job by Id
      parameters:
        - name: id
          in: path
          required: true
          description: Job ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJob'
      responses:
        '200':
          description: Job updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateJobResponse'
        '404':
          description: Job not found
        '500':
          description: Internal server error
  /deleteJob/{id}:
    delete:
      summary: Delete a job
      tags:
        - Jobs
      description: Delete an job by Id
      parameters:
        - name: id
          in: path
          required: true
          description: Job ID
          schema:
            type: string
      responses:
        '200':
          description: Job deletion successfull
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteJobResponse'
        '400':
          description: Job not found
        '500':
          description: Failed to delete the job
components:
  schemas:
    JobInput:
      $ref: '#/components/schemas/Job'
    JobResponse:
      type: object
      properties:
        id:
          type: string
          description: Auto-generated MongoDB ID
          example: 507f1f77bcf86cd799439011
        createdAt:
          type: string
          format: date-time
          example: '2024-01-08T10:30:00Z'
        updatedAt:
          type: string
          format: date-time
          example: '2024-01-08T10:30:00Z'
      required:
        - id
        - createdAt
        - updatedAt
    UpdateJob:
      type: object
      description: Fields that can be updated for a job
      properties:
        title:
          type: string
          example: Backend Developer
        department:
          type: string
          example: Engineering
        location:
          type: string
          example: Chennai, India
        status:
          type: string
          enum:
            - OPEN
            - CLOSED
            - HOLD
          example: OPEN
        headcount:
          type: integer
          example: 3
          minimum: 1
        description:
          type: string
          example: Responsible for backend APIs
        requirements:
          type: string
          example: Node.js, MongoDB, REST APIs
    UpdateJobResponse:
      type: object
      properties:
        id:
          type: string
          description: Auto generated MongoDB ID
          example: 507f1f77bcf86cd799439011
        message:
          type: string
          description: Message for successfull updation
          example: Job updated successfully
      required:
        - id
        - message
    DeleteJobResponse:
      type: object
      properties:
        message:
          type: string
          description: Message for successfull deletion of job
          example: Job deleted successfully
    Job:
      type: object
      required:
        - title
        - department
        - location
        - status
        - headcount
        - description
        - requirements
      properties:
        title:
          type: string
          example: Senior Backend Engineer
        department:
          type: string
          example: Engineering
        location:
          type: string
          example: Remote
        status:
          type: string
          enum:
            - OPEN
            - CLOSED
            - HOLD
          example: OPEN
        headcount:
          type: integer
          minimum: 1
          example: 3
        description:
          type: string
          description: Detailed job description
          example: We are looking for a backend engineer
        requirements:
          type: string
          description: Job requirements and skills
          example: 5+ years Node.js experience
